USE WALTRONICS;
GO

DROP TABLE Employee.Session;

CREATE TABLE Employee.Session (
	EmployeeID	UNIQUEIDENTIFIER	NOT NULL,
	SessionID	CHAR(36)			NOT NULL UNIQUE,
	LoginDate	DATETIME			NOT NULL DEFAULT GETDATE(),
	PRIMARY KEY (EmployeeID),
	FOREIGN KEY (EmployeeID) REFERENCES Employee.Employee (EmployeeID) ON DELETE CASCADE
);

ALTER TABLE Employee.Session
ADD CONSTRAINT DK_Session
DEFAULT GETDATE() FOR LoginDate;

ALTER TABLE Employee.Session
ALTER COLUMN SessionID VARBINARY(MAX);