USE WALTRONICS;
GO

DROP PROCEDURE Appointment.EasyInsertNote;
GO

CREATE PROCEDURE Appointment.EasyInsertNote (
	@SessionID		CHAR(36),
	@AppointmentID	UNIQUEIDENTIFIER,
	@Head			VARCHAR(100),
	@Body			VARCHAR(500),
	@ShowCustomer	BIT = 0,
	@Sharees		VARCHAR(MAX)
) 
AS
BEGIN
	SET NOCOUNT ON;
	SET XACT_ABORT ON;
	BEGIN TRANSACTION;

	COMMIT TRANSACTION;
END;
GO

