USE WALTRONICS;
GO

DROP TABLE Appointment.ID;

CREATE TABLE Appointment.ID (
	AppointmentID	UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	CustomerID		UNIQUEIDENTIFIER NOT NULL,
	PRIMARY KEY (AppointmentID),
	FOREIGN KEY (CustomerID) REFERENCES Customer.Customer (CustomerID) ON DELETE CASCADE
);

ALTER TABLE Appointment.ID
ADD CONSTRAINT DK_App 
DEFAULT NEWSEQUENTIALID() FOR AppointmentID;